### ISSUE TITLE
mongodb_user: error when updating user with different roles

### ISSUE THREAD

**Issue by PDmatrix** [ansible-collections/community.mongodb#278]
##### SUMMARY

With `update_password: on_create` user creates first time I run playbook. But if I want to change user roles and run the same playbook it fails with error: `pymongo.errors.OperationFailure: "pwd" had the wrong type. Expected string, found null` 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mongodb_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_REMOTE_USER(env: ANSIBLE_REMOTE_USER) = wof_ansible
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/.galaxy_roles']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
MongoDB shell version v4.2.0
git version: a4b751dcf51dd249c5865812b390cfd1c0129c30
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
```

##### STEPS TO REPRODUCE

First, we run this playbook

```yaml
---
- name: Setup MongoDB
  hosts:
    - mongodb

  vars:
    myuser:
      user: myuser
      password: secret
      db: admin
      roles:
        - dbAdmin

  tasks:
    - name: Create or update mongodb user
      community.mongodb.mongodb_user:
        name: "{{ myuser.user }}"
        roles: "{{ myuser.roles }}"
        database: "{{ myuser.db }}"
        password: "{{ myuser.password }}"
        replica_set: rs01
        update_password: on_create
```

After that, we run same playbook but with different role

```yaml
---
- name: Setup MongoDB
  hosts:
    - mongodb

  vars:
    myuser:
      user: myuser
      password: secret
      db: admin
      roles:
        - userAdmin

  tasks:
    - name: Create or update mongodb user
      community.mongodb.mongodb_user:
        name: "{{ myuser.user }}"
        roles: "{{ myuser.roles }}"
        database: "{{ myuser.db }}"
        password: "{{ myuser.password }}"
        replica_set: rs01
        update_password: on_create
```

##### EXPECTED RESULTS

I expect that second playbook run successfully and in mongodb I will have user `myuser` with role `userAdmin` and same password

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.mongodb.mongodb_user_payload_oiq6nycx/ansible_community.mongodb.mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 417, in main
  File "/tmp/ansible_community.mongodb.mongodb_user_payload_oiq6nycx/ansible_community.mongodb.mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 257, in user_add
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 740, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 637, in _command
    client=self.__client)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 694, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/network.py", line 161, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/helpers.py", line 160, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: "pwd" had the wrong type. Expected string, found null, full error: {'operationTime': Timestamp(1609880394, 3), 'ok': 0.0, 'errmsg': '"pwd" had the wrong type. Expected string, found null', 'code': 14, 'codeName': 'TypeMismatch', '$clusterTime': {'clusterTime': Timestamp(1609880394, 3), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}}
```

Issue in these lines
https://github.com/ansible-collections/community.mongodb/blob/master/plugins/modules/mongodb_user.py#L410
and https://github.com/ansible-collections/community.mongodb/blob/master/plugins/modules/mongodb_user.py#L257
If the user exists, password is set to `None` and in function `user_add` we pass pwd as `None`. I suspect that `pymongo` doesn't like that 🤔

**Comment by rhysmeister** [comment]
Thanks for the bug report. A fix for this was just merged. You can grab the latest build from the release page.

**Comment by usefree** [comment]
Hello, [rhysmeister](https://github.com/rhysmeister), thanks for fix, it helps, but in case to use param 
`mongodb_user_update_password: on_create`
still bug present
ubuntu 20.04
ansible-2.10.0
community.mongodb 1.7.2
pymongo-4.6.2
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_mongodb_user_payload_p8nu2nve/ansible_mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 376, in main
  File "/tmp/ansible_mongodb_user_payload_p8nu2nve/ansible_mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 230, in user_add
  File "/usr/local/lib/python3.8/dist-packages/pymongo/database.py", line 738, in command
    return self._command(sock_info, command, slave_ok, value,
  File "/usr/local/lib/python3.8/dist-packages/pymongo/database.py", line 626, in _command
    return sock_info.command(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
  File "/usr/local/lib/python3.8/dist-packages/pymongo/network.py", line 159, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/helpers.py", line 164, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: "pwd" had the wrong type. Expected string, found null, full error: {'operationTime': Timestamp(1711195306, 24), 'ok': 0.0, 'errmsg': '"pwd" had the wrong type. Expected string, found null', 'code': 14, 'codeName': 'TypeMismatch', '$clusterTime'...
```
workaround to use 
`mongodb_user_update_password: always`

**Comment by rhysmeister** [comment]
Hello, @usefree,

Can you please include the exact task call you're using here? Does this error always occur, i.e. on create and update runs, or only after an update. The on_create option is tested in our CI and that passes. 

Rhys

**Comment by usefree** [comment]
error appear only with update run
task: 
```
  tasks:
    - name: create normal users with replicaset
      mongodb_user:
        database: "{{ item.database }}"
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        update_password: "{{ mongodb_user_update_password }}"
        roles: "{{ item.roles }}"
        login_user: "{{ mongodb_user_admin_name }}"
        login_password: "{{ mongodb_user_admin_password }}"
        login_port: "{{ mongodb_login_port|default(27017) }}"
        login_host: "{{ mongodb_login_host|default('localhost') }}"
        replica_set: "{{ mongodb_replication_replset }}"
        ssl: "{{ True if mongodb_net_ssl_mode == 'requireSSL' else False }}"
      with_items:
        - "{{ mongodb_users | default([]) }}"
      when: ( mongodb_replication_replset
            and mongodb_master is defined and mongodb_master )
        and mongodb_master is defined and mongodb_master )
      no_log: false
      tags:
        - never
        - mongodb_users
```
and variables part :
```
mongodb_users:
  - name: monitoringagent
    password: pass
    roles:
      - { role: "clusterMonitor", db: admin }
      - { role: "readAnyDatabase", db: admin }
      - { role: "readWrite", db: "local" }
    database: admin
```

**Comment by rhysmeister** [comment]
Can you try using the full module path, e.g. `community.mongodb.mongodb_user`?

**Comment by usefree** [comment]
i used ansible version 2.9.27 and option `mongodb_user_update_password: on_create` works without errors

**Comment by rhysmeister** [comment]
The mongodb_user module was included in Ansible before collections existed and I think it still is... but they include an old version. When you don't use the full path you use this older version of the module. Even when you're using one of these older versions of ansible you should use the full module path, e.g. community.mongodb.mongodb_user. This way you know you're not using an older version of the module.
