### ISSUE TITLE
mongodb_info fails with bson.timestamp.Timestamp type error

### ISSUE THREAD

**Issue by apinter** [ansible-collections/community.mongodb#462]
##### SUMMARY
Hi,

Have a replica set with `Mongo 5.0.6`, and when I try to run `community.mongodb.mongodb_info` to gather info from the rs it errors out with `TypeError: Value of unknown type: <class 'bson.timestamp.Timestamp'>, Timestamp(1650609911, 1)` for some reason. Absolutely possible that I'm doing something wrong though.
 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`mongodb_info`

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = /home/apinter/.ansible.cfg
  configured module search path = ['/home/apinter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/apinter/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/apinter/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/apinter/.local/bin/ansible
  python version = 3.8.13 (default, Mar 26 2022, 22:17:55) [GCC]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/apinter/.local/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.7.0  

# /home/apinter/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.7.0  
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
CACHE_PLUGIN(/home/apinter/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/apinter/.ansible.cfg) = /tmp
DEFAULT_FORKS(/home/apinter/.ansible.cfg) = 10
DEFAULT_GATHERING(/home/apinter/.ansible.cfg) = smart
DEFAULT_JINJA2_EXTENSIONS(/home/apinter/.ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_STDOUT_CALLBACK(/home/apinter/.ansible.cfg) = yaml

```

##### OS / ENVIRONMENT

Running Ansible on openSUSE Tumbleweed, installed from PyPi.
Target hosts:
```
mongo-2 | CHANGED | rc=0 >>
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

mongo-1 | CHANGED | rc=0 >>
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

mongo-0 | CHANGED | rc=0 >>
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Kernel:
```
mongo-2 | CHANGED | rc=0 >>
Linux loyalty-sandbox-mongo-2 5.13.0-1023-gcp #28~20.04.1-Ubuntu SMP Wed Mar 30 03:51:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

mongo-0 | CHANGED | rc=0 >>
Linux loyalty-sandbox-mongo-0 5.13.0-1023-gcp #28~20.04.1-Ubuntu SMP Wed Mar 30 03:51:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

mongo-1 | CHANGED | rc=0 >>
Linux loyalty-sandbox-mongo-1 5.13.0-1023-gcp #28~20.04.1-Ubuntu SMP Wed Mar 30 03:51:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

pymongo version:

```
pymongo                4.1.0               
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Testing module info
  become: false
  hosts: mongo-0
  tasks:
    - name: test run
      community.mongodb.mongodb_info:
        auth_mechanism: PLAIN
        login_user: adathor
        login_password: "example"
        login_database: "admin"
        login_host: 127.0.0.1
        login_port: 27017
      register: mongo_info  
    - name: print results
      ansible.builtin.debug:
        var: mongo_info
```

##### EXPECTED RESULTS

I can acquire information from the nodes.

##### ACTUAL RESULTS

Play fails with:

```paste below
[I] ◆ mongo ❯❯❯ ansible-playbook -i mongo_inv mongo_info.yml -vvv 
ansible-playbook [core 2.12.4]
  config file = /home/apinter/.ansible.cfg
  configured module search path = ['/home/apinter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/apinter/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/apinter/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/apinter/.local/bin/ansible-playbook
  python version = 3.8.13 (default, Mar 26 2022, 22:17:55) [GCC]
  jinja version = 3.0.3
  libyaml = True
Using /home/apinter/.ansible.cfg as config file
host_list declined parsing /home/apinter/Project/Antavo/mongo/mongo_inv as it did not pass its verify_file() method
script declined parsing /home/apinter/Project/Antavo/mongo/mongo_inv as it did not pass its verify_file() method
auto declined parsing /home/apinter/Project/Antavo/mongo/mongo_inv as it did not pass its verify_file() method
Parsed /home/apinter/Project/Antavo/mongo/mongo_inv inventory source with ini plugin
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: mongo_info.yml *************************************************************************************************************************************************************
1 plays in mongo_info.yml

PLAY [Testing module info] ***********************************************************************************************************************************************************
META: ran handlers

TASK [test run] **********************************************************************************************************************************************************************
task path: /home/apinter/Project/Antavo/mongo/mongo_info.yml:6
<10.39.1.4> ESTABLISH SSH CONNECTION FOR USER: attila.pinter
<10.39.1.4> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=3600s -o ServerAliveInterval=50 -o ForwardAgent=yes -o PreferredAuthentications=publickey -o 'IdentityFile="/home/apinter/.ssh/antavo_gcp"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="attila.pinter"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 'ProxyCommand=ssh -W %h:%p -o StrictHostKeyChecking=no -q -i ~/.ssh/antavo_gcp attila.pinter@35.228.180.200' -o 'ControlPath="/home/apinter/.ansible/cp/27ad9b49ba"' 10.39.1.4 '/bin/sh -c '"'"'echo ~attila.pinter && sleep 0'"'"''
<10.39.1.4> (0, b'/home/attila.pinter\n', b'')
<10.39.1.4> ESTABLISH SSH CONNECTION FOR USER: attila.pinter
<10.39.1.4> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=3600s -o ServerAliveInterval=50 -o ForwardAgent=yes -o PreferredAuthentications=publickey -o 'IdentityFile="/home/apinter/.ssh/antavo_gcp"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="attila.pinter"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 'ProxyCommand=ssh -W %h:%p -o StrictHostKeyChecking=no -q -i ~/.ssh/antavo_gcp attila.pinter@35.228.180.200' -o 'ControlPath="/home/apinter/.ansible/cp/27ad9b49ba"' 10.39.1.4 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/attila.pinter/.ansible/tmp `"&& mkdir "` echo /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885 `" && echo ansible-tmp-1650610757.8125987-14255-214086540587885="` echo /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885 `" ) && sleep 0'"'"''
<10.39.1.4> (0, b'ansible-tmp-1650610757.8125987-14255-214086540587885=/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885\n', b'')
Using module file /home/apinter/.ansible/collections/ansible_collections/community/mongodb/plugins/modules/mongodb_info.py
<10.39.1.4> PUT /home/apinter/.ansible/tmp/ansible-local-14236_o1b4j75/tmp60gl4lr2 TO /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py
<10.39.1.4> SSH: EXEC sftp -b - -o ControlMaster=auto -o ControlPersist=3600s -o ServerAliveInterval=50 -o ForwardAgent=yes -o PreferredAuthentications=publickey -o 'IdentityFile="/home/apinter/.ssh/antavo_gcp"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="attila.pinter"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 'ProxyCommand=ssh -W %h:%p -o StrictHostKeyChecking=no -q -i ~/.ssh/antavo_gcp attila.pinter@35.228.180.200' -o 'ControlPath="/home/apinter/.ansible/cp/27ad9b49ba"' '[10.39.1.4]'
<10.39.1.4> (0, b'sftp> put /home/apinter/.ansible/tmp/ansible-local-14236_o1b4j75/tmp60gl4lr2 /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py\n', b'')
<10.39.1.4> ESTABLISH SSH CONNECTION FOR USER: attila.pinter
<10.39.1.4> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=3600s -o ServerAliveInterval=50 -o ForwardAgent=yes -o PreferredAuthentications=publickey -o 'IdentityFile="/home/apinter/.ssh/antavo_gcp"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="attila.pinter"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 'ProxyCommand=ssh -W %h:%p -o StrictHostKeyChecking=no -q -i ~/.ssh/antavo_gcp attila.pinter@35.228.180.200' -o 'ControlPath="/home/apinter/.ansible/cp/27ad9b49ba"' 10.39.1.4 '/bin/sh -c '"'"'chmod u+x /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/ /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py && sleep 0'"'"''
<10.39.1.4> (0, b'', b'')
<10.39.1.4> ESTABLISH SSH CONNECTION FOR USER: attila.pinter
<10.39.1.4> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=3600s -o ServerAliveInterval=50 -o ForwardAgent=yes -o PreferredAuthentications=publickey -o 'IdentityFile="/home/apinter/.ssh/antavo_gcp"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="attila.pinter"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 'ProxyCommand=ssh -W %h:%p -o StrictHostKeyChecking=no -q -i ~/.ssh/antavo_gcp attila.pinter@35.228.180.200' -o 'ControlPath="/home/apinter/.ansible/cp/27ad9b49ba"' -tt 10.39.1.4 '/bin/sh -c '"'"'/usr/bin/python3 /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py && sleep 0'"'"''
<10.39.1.4> (1, b'Traceback (most recent call last):\r\n  File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 107, in <module>\r\n    _ansiballz_main()\r\n  File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 47, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.community.mongodb.plugins.modules.mongodb_info\', init_globals=dict(_module_fqn=\'ansible_collections.community.mongodb.plugins.modules.mongodb_info\', _modlib_path=modlib_path),\r\n  File "/usr/lib/python3.8/runpy.py", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_info.py", line 313, in <module>\r\n  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_info.py", line 309, in main\r\n  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/basic.py", line 1518, in exit_json\r\n  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/basic.py", line 1511, in _return_formatted\r\n  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/common/parameters.py", line 890, in remove_values\r\n  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/common/parameters.py", line 461, in _remove_values_conditions\r\nTypeError: Value of unknown type: <class \'bson.timestamp.Timestamp\'>, Timestamp(1650610761, 1)\r\n', b'Shared connection to 10.39.1.4 closed.\r\n')
<10.39.1.4> Failed to connect to the host via ssh: Shared connection to 10.39.1.4 closed.
<10.39.1.4> ESTABLISH SSH CONNECTION FOR USER: attila.pinter
<10.39.1.4> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=3600s -o ServerAliveInterval=50 -o ForwardAgent=yes -o PreferredAuthentications=publickey -o 'IdentityFile="/home/apinter/.ssh/antavo_gcp"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="attila.pinter"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 'ProxyCommand=ssh -W %h:%p -o StrictHostKeyChecking=no -q -i ~/.ssh/antavo_gcp attila.pinter@35.228.180.200' -o 'ControlPath="/home/apinter/.ansible/cp/27ad9b49ba"' 10.39.1.4 '/bin/sh -c '"'"'rm -f -r /home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/ > /dev/null 2>&1 && sleep 0'"'"''
<10.39.1.4> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.mongodb.plugins.modules.mongodb_info', init_globals=dict(_module_fqn='ansible_collections.community.mongodb.plugins.modules.mongodb_info', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_info.py", line 313, in <module>
  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_info.py", line 309, in main
  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/basic.py", line 1518, in exit_json
  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/basic.py", line 1511, in _return_formatted
  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/common/parameters.py", line 890, in remove_values
  File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/common/parameters.py", line 461, in _remove_values_conditions
TypeError: Value of unknown type: <class 'bson.timestamp.Timestamp'>, Timestamp(1650610761, 1)
fatal: [mongo-0]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to 10.39.1.4 closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 107, in <module>
        _ansiballz_main()
      File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/attila.pinter/.ansible/tmp/ansible-tmp-1650610757.8125987-14255-214086540587885/AnsiballZ_mongodb_info.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.mongodb.plugins.modules.mongodb_info', init_globals=dict(_module_fqn='ansible_collections.community.mongodb.plugins.modules.mongodb_info', _modlib_path=modlib_path),
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_info.py", line 313, in <module>
      File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_info.py", line 309, in main
      File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/basic.py", line 1518, in exit_json
      File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/basic.py", line 1511, in _return_formatted
      File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/common/parameters.py", line 890, in remove_values
      File "/tmp/ansible_community.mongodb.mongodb_info_payload_cnnhz9mn/ansible_community.mongodb.mongodb_info_payload.zip/ansible/module_utils/common/parameters.py", line 461, in _remove_values_conditions
    TypeError: Value of unknown type: <class 'bson.timestamp.Timestamp'>, Timestamp(1650610761, 1)
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ***************************************************************************************************************************************************************************
mongo-0                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by rhysmeister** [comment]
Hello @apinter,

I don't think you're doing anything wrong here. I think I've seen this issue before. I think this is actually due to a limitation in Ansible itself. There is a similar issue here...

https://github.com/ansible-collections/community.mongodb/issues/462

I'm uncertain if Ansible would want to add these specialised data type to their parser. I'm uncertain if there any way around this at the module python level could be done. You could use the filter parameter of the module to exclude this property from the output. @Andersson007 would you have any input here? I ran into this problem when creating a mongodb_document module and I remember getting this error with MongoDB ObjectIds.

Cheers,

Rhys

**Comment by apinter** [comment]
@rhysmeister Hey there, thanks for the answer. TBH was hoping that I'm messing up ^-^. Anyhow, I tried to filter out things, but it doesn't seem to change the output and it does seem to work for some cases, for example only getting back the users did work seemingly, however, that was giving a different type of error:

```
TASK [test run] ******************************************************************************************************************************
ok: [mongo-0]

TASK [print results] *************************************************************************************************************************
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible_collections.community.general.plugins.callback.yaml.CallbackModule object at 0x7f425746ec10>): 'utf-8' codec can't encode
characters in position 0-1: surrogates not allowed
``` 

Solution to that was pretty simple, just disabled the `#stdout_callback = yaml`, but that has not much to do with the mongo collection. What is that from the list of allowable values only general, and parameters are giving this error. Could this have something to do with the _Mongodb_ version maybe? Have a few older ones (3.4) where I could try, but only Monday can access it.

**Comment by rhysmeister** [comment]
Hello @apinter,

I think at least partially to do with the version. I've just checked the CI and we test against the latest available MongoDB (currently 5.0.7). That seems fine and we also do a test where we return all data....

https://github.com/ansible-collections/community.mongodb/blob/master/tests/integration/targets/mongodb_info/tasks/mongodb_info.yml

This is tested against a single standalone instance though. You're testing against a replicaset member?

Rhys

**Comment by apinter** [comment]
> This is tested against a single standalone instance though. You're testing against a replicaset member?

Yes, no matter which I run against I get back the same result though.

**Comment by rhysmeister** [comment]
> > This is tested against a single standalone instance though. You're testing against a replicaset member?
> 
> Yes, no matter which member I run against I get back the same result though.

Yes, I would expect that. I guess that replicasets/sharded cluster member instance have additional data present that standalone instances don't have.

**Comment by Andersson007** [comment]
hi, folks! @apinter thanks for creating the issue! @rhysmeister thanks for mentioning!

Yes, it's Ansible's limitation. I got similar issues in c.postgres with the `timestamp` data type and with something else.
I submitted a PR to ansible core to convert it to string but they said that it should be converted on the client's side.
So what we need to add is a check, i.e. if value is of `bson.timestamp.Timestamp`, make it a string or whatever so Ansible can return it.

If the solution seems fine to you and anyone wants to submit a PR, i'd be happy to review. If no one wants, let me know, i'll take a look.

**Comment by apinter** [comment]
> hi, folks! @apinter thanks for creating the issue! @rhysmeister thanks for mentioning!
> 
> Yes, it's Ansible's limitation. I got similar issues in c.postgres with the `timestamp` data type and with something else. I submitted a PR to ansible core to convert it to string but they said that it should be converted on the client's side. So what we need to add is a check, i.e. if value is of `bson.timestamp.Timestamp`, make it a string or whatever so Ansible can return it.
> 
> If the solution seems fine to you and anyone wants to submit a PR, i'd be happy to review. If no one wants, let me know, i'll take a look.

Hi @Andersson007, big thanks for the explanation. This `bson` value seems a bit funky indeed. Could take a swing at it, but have free time only on Friday.

**Comment by Andersson007** [comment]
>Hi @Andersson007, big thanks for the explanation. This bson value seems a bit funky indeed. Could take a swing at it, but have free time only on Friday.

@apinter great, thanks!
The following things can be helpful:
- [quick start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html)
- as an example see how the `convert_to_supported` function is used in the [postgresql_query](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_query.py) module

If any help needed, let us know

**Comment by apinter** [comment]
Sorry guys, didn't forget about this, but $DayJob is a bit messy, will try and sort it this week. Apologies :(

**Comment by rhysmeister** [comment]
No problem. This will need tests against a replicaset. I can help with that. Ping me when you're ready.

**Comment by rhysmeister** [comment]
I've added a fix with unit tests for this. I wasn't able to replicate this problem in the wild against the latest version 5 of MongoDB (5.0.10) but hopefully it's covered. Please reopen if there's still a problem.

https://github.com/ansible-collections/community.mongodb/pull/488
