### ISSUE TITLE
Admin user creation in mongodb_auth fails because authentication is not enabled ?

### ISSUE THREAD

**Issue by alterphp** [ansible-collections/community.mongodb#535]
##### SUMMARY

Here is my playbook content
```
---
- hosts: all

  become: true

  pre_tasks:

    - name: Install module PyMongo
      ansible.builtin.apt:
        name: python3-pymongo
        state: present

  roles:
    - community.mongodb.mongodb_linux
    - community.mongodb.mongodb_repository
    - community.mongodb.mongodb_install
    - community.mongodb.mongodb_mongod
    - community.mongodb.mongodb_auth

```

It fails at task `community.mongodb.mongodb_auth : Add mongo admin user with localhost exception` with `command createUser requires authentication, full error: {'ok': 0.0, 'errmsg': 'command createUser requires authentication', 'code': 13, 'codeName': 'Unauthorized'}`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.mongodb.mongodb_auth

##### ANSIBLE VERSION
```
ansible [core 2.13.7]
  config file = <path-to-project>/ansible-mongodb-logs/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = $HOME/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
community.mongodb             1.4.2
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH('<path-to-project>/ansible-mongodb-logs/ansible.cfg) = ['<path-to-project>/ansible-mongodb-logs/roles']
HOST_KEY_CHECKING(<path-to-project>/ansible-mongodb-logs/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 22.10 (local)
Debian 11 (remote)

##### STEPS TO REPRODUCE
Play the playbook printed above, without any variable override, it will fail. I personnally override some of them (mongodb_admin_pwd at least), but it fails the same way.

The task `Add mongo admin user with localhost exception` (https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_auth/tasks/main.yml#L38) uses `community.mongodb.mongodb_user` that does not work before authentication is enabled (it's done just after trying to add admin user).

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.mongodb.mongodb_user_payload_tys0a5kq/ansible_community.mongodb.mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 389, in main
  File "/tmp/ansible_community.mongodb.mongodb_user_payload_tys0a5kq/ansible_community.mongodb.mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 266, in user_add
  File "/usr/lib/python3/dist-packages/pymongo/database.py", line 738, in command
    return self._command(sock_info, command, slave_ok, value,
  File "/usr/lib/python3/dist-packages/pymongo/database.py", line 626, in _command
    return sock_info.command(
  File "/usr/lib/python3/dist-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
  File "/usr/lib/python3/dist-packages/pymongo/network.py", line 159, in command
    helpers._check_command_response(
  File "/usr/lib/python3/dist-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response,
pymongo.errors.OperationFailure: command createUser requires authentication, full error: {'ok': 0.0, 'errmsg': 'command createUser requires authentication', 'code': 13, 'codeName': 'Unauthorized'}
fatal: [mongodb-log1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_mechanism": null,
            "connection_options": null,
            "create_for_localhost_exception": "/root/mongodb_admin.success",
            "database": "admin",
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": null,
            "login_port": 27017,
            "login_user": null,
            "name": "admin",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "replica_set": null,
            "roles": [
                "root"
            ],
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "state": "present",
            "strict_compatibility": true,
            "update_password": "always"
        }
    },
    "msg": "Unable to add or update user: command createUser requires authentication, full error: {'ok': 0.0, 'errmsg': 'command createUser requires authentication', 'code': 13, 'codeName': 'Unauthorized'}"
}

```

**Comment by alterphp** [comment]
Official MongoDB documentation (5.0 and 6.0) states that localhost exception (the ability to create the first admin user after installation) is available after enabling authentication.

https://www.mongodb.com/docs/manual/core/localhost-exception/#:~:text=After%20you%20enable%20access%20control%2C%20connect%20to%20the%20localhost%20interface%20and%20create%20the%20first%20user%20in%20the%20admin%20database.

**Comment by cognifloyd** [comment]
They changed the localhost exception in 5+? Oh ugh. I'll read up.
